// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package algolia

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	DestinationConfigApiKey        = "apiKey"
	DestinationConfigApplicationID = "applicationID"
	DestinationConfigIndexName     = "indexName"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		DestinationConfigApiKey: {
			Default:     "",
			Description: "API key for Algolia APIs.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigApplicationID: {
			Default:     "",
			Description: "Application ID for Algolia.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		DestinationConfigIndexName: {
			Default:     "",
			Description: "IndexName is the name of the index where records get written into.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
